### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by metacosm** [snowdrop/spring-boot-cloud-devex#58]
We should rename the project to something more explicit if we're going to keep it…

**Comment by cmoulliard** [comment]
Propositions @metacosm @geoand @lincolnthree ?

- springboot-dev-experience
- sprinboot-cloud-experience
...

**Comment by geoand** [comment]
`springboot-cloud-devex`?

**Comment by metacosm** [comment]
Whatever we choose, we should wait until we figure out how things shape up once we have merged code in `odo`…

**Comment by lincolnthree** [comment]
snowdrop-springboot-generator
snowdrop-cli ?

**Comment by cmoulliard** [comment]
I vote for `github.com/snowdrop/springboot-cloud-devex` and you @iocanel @lincolnthree @gytis @metacosm @geoand ?

**Comment by geoand** [comment]
Me too

**Comment by gytis** [comment]
As per convention we should keep spring-boot as separate words. But other than that sounds good to me

**Comment by geoand** [comment]
Good point @gytis!

**Comment by cmoulliard** [comment]
So, the name will be then `spring-boot-cloud-devex`

**Comment by lincolnthree** [comment]
Works for me
