### ISSUE TITLE
Remove init command.

### ISSUE THREAD

**Issue by metacosm** [snowdrop/spring-boot-cloud-devex#68]
The `init` operations should occur on demand when a user initiates a command and the tool hasn't already initialized.

**Comment by cmoulliard** [comment]
Do you mean that if I execute `sd create` and if a deploymentConfig, service doesn't yet exist, then they will be created for this component ? @metacosm

**Comment by metacosm** [comment]
Well, it's not needed for `create` but, yes. If a user creates a project then decides to `push` for example, `init` will be called transparently without having to call it explicitly.

**Comment by metacosm** [comment]
Closed by #69
